fakijiji/urls.py
from django.contrib import admin
from django.urls import path, include
from items import views

# All the possible url paths from the root
urlpatterns = [
    path('', views.guestItems),
    path('admin/', admin.site.urls),
    path('home/', include('login.urls')),
    path('items/', include('items.urls')),
    path('profile/', include('userprofile.urls')),
]

items/urls.py
from django.urls import path
from . import views

app_name = 'item'

# All the possible url paths related to items
urlpatterns = [
    path('', views.customerItems, name='home'),
    path('additems/', views.addItems),
    path('<int:pk>', views.ViewItem.as_view(), name='view_item'),
    path('<int:pk>/like', views.likeItem, name='like_item'),
    path('<int:pk>/rate', views.rateItem, name='rate_item'),
    path('<int:pk>/modifyItem/', views.ModifyItem.as_view(), name="modify_item"),
    path('<int:pk>/deleteItem/', views.DeleteItem.as_view(template_name='items/deleteitem.html'), name="delete_item"),
    path('<int:pk>/buyItem/', views.BuyItem.as_view(), name="buy_item"),
]

items/models.py
from login.models import UserProfile
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Creating the Item model with its required attributes


class Item(models.Model):
    img = models.ImageField(upload_to='images/', default="images/default.jpg")
    title = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    description = models.TextField(max_length=6000, default='')
    sold = models.BooleanField(default=False)
    likes = models.IntegerField(default=0)
    rate = models.DecimalField(max_digits=2, decimal_places=1, default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

# Creating the LogItem model with its required attributes


class LogItem(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    creationDate = models.DateTimeField('created', default=timezone.now())
    lastModified = models.DateTimeField('modified', default=timezone.now())

items/forms.py
from django import forms
from django.db import models
from .models import Item

# Form to add items to the database


class AddItemForm(forms.Form):
    name = forms.CharField(label="Item Name:", max_length=200)
    price = forms.CharField(label="Item Price:", max_length=200)
    description = forms.CharField(label="Description:", max_length=200)
    image = forms.ImageField(label="Item Image")

    class Meta:
        model = Item
        fields = ('name', 'price', 'description', 'image')

# Form to modify items on the database


class ModifyItemForm(forms.Form):
    title = forms.CharField(label="Title")
    price = forms.DecimalField(label="Price")
    description = forms.CharField(label="Description")

items/views.py
import decimal
from django.forms.utils import flatatt
from django.urls import reverse
from django.contrib.auth import logout
from django.forms.models import BaseModelForm, BaseModelFormSet
from django.http.response import HttpResponseRedirect
from login.models import UserProfile
from django.views import generic
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import redirect
from items.models import Item, LogItem
from .forms import AddItemForm
from django.views.generic.edit import DeleteView, UpdateView
from django.utils import timezone

# Method to


def getUser(req):
    user = req.user
    if user.is_authenticated:
        userprofile = UserProfile.objects.get(user_id=user.id)
        return {'userprofile': userprofile}
    return {}

# Method to display all the items as a guest


def guestItems(request):
    logout(request)
    items = Item.objects.all().order_by('-likes')
    if request.method == "POST":
        if len(request.POST.get('search')) != 0:
            items = Item.objects.filter(title__contains=request.POST.get('search')).order_by('-likes')
    context = {'items': items}
    template = loader.get_template('items/guestitems.html')
    return HttpResponse(template.render(context, request))

# Method to display all the items as a customer with additional functions


def customerItems(request):
    user = request.user
    if user.is_authenticated:
        items = Item.objects.all().order_by('-likes')
        if request.method == "POST":
            if len(request.POST.get('search')) != 0:
                items = Item.objects.filter(title__contains=request.POST.get('search')).order_by('-likes')
        username = request.user.username
        context = {"items": items, "username": username}
        context.update(getUser(request))
        template = loader.get_template('items/customeritems.html')
        return HttpResponse(template.render(context, request))
    return redirect('/')

# Method to add items to the database as a customer only


def addItems(request):
    form = AddItemForm(request.POST or None, request.FILES or None)
    user = request.user

    if not user.is_authenticated:
        return redirect('/home')

    if form.is_valid():
        name = form.cleaned_data.get('name')
        price = form.cleaned_data.get('price')
        description = form.cleaned_data.get('description')
        image = form.cleaned_data.get('image')
        Item.objects.create(
            title=name,
            price=price,
            description=description,
            img=image,
            user=user
        )
        LogItem.objects.create(
            title=name,
            author=user,
            creationDate=timezone.now(),
            lastModified=timezone.now())
        return redirect('/items')

    context = {'form': form}
    context.update(getUser(request))
    template = loader.get_template('items/additems.html')
    return HttpResponse(template.render(context, request))

# Method to view an individual items with additional information


class ViewItem(generic.DetailView):
    model = Item
    template_name = 'items/item.html'

    def get(self, request, pk):
        item = Item.objects.get(id=pk)
        context = {"item": item}
        context.update(getUser(request))
        template = loader.get_template('items/item.html')
        return HttpResponse(template.render(context, request))

# Method to buy an item, change the owner of that item, set to sold, transfer the balance amounts, save it to the database and redirect the user to the items page


class BuyItem(UpdateView):
    model = Item
    fields = ['sold', 'user']
    template_name = 'items/buyitem.html'

    def get(self, request, pk):
        user = request.user
        if not user.is_authenticated:
            return redirect('/home')
        item = Item.objects.get(id=pk)
        context = {"item": item, 'sufficientBalance': True}
        context.update(getUser(request))
        template = loader.get_template('items/buyitem.html')
        return HttpResponse(template.render(context, request))

    def post(self, request, pk, *args, **kwargs) -> HttpResponse:
        item = Item.objects.get(id=pk)
        user = UserProfile.objects.get(user_id=request.user.id)
        user2 = UserProfile.objects.get(user_id=item.user_id)
        if user.balance >= item.price:
            item.user_id = user.user_id
            item.sold = True
            user.balance -= item.price
            user2.balance += item.price
            item.save()
            user.save()
            user2.save()
            return redirect('/items/')
        context = {"item": item, 'sufficientBalance': False}
        context.update(getUser(request))
        template = loader.get_template('items/buyitem.html')
        return HttpResponse(template.render(context, request))
        # return HttpResponseRedirect(reverse('item:buy_item', args=[str(pk)]))

# Method to like an item and save it to the database


def likeItem(request, pk):
    item = get_object_or_404(Item, id=request.POST.get('like'))
    item.likes += 1
    item.save()
    return redirect('/items/' + str(pk))

# Method to rate an item and save it to the database


def rateItem(request, pk):
    item = get_object_or_404(Item, id=request.POST.get('ratebtn'))
    if item.rate != 0:
        item.rate = (item.rate + decimal.Decimal(float(request.POST.get('rate')))) / 2
    else:
        item.rate = request.POST.get('rate')
    item.save()
    return redirect('/items/' + str(pk))

# Method to delete an item from the database


class DeleteItem(DeleteView):
    model = Item
    success_url = "/items"

# Method to modify an item in the database


class ModifyItem(UpdateView):
    model = Item
    fields = ['title', 'price', 'description']
    template_name = 'items/modifyitem.html'

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        pk = self.get_object().pk
        item = Item.objects.get(id=pk)
        if form.is_valid():
            item.title = form.cleaned_data.get('title')
            item.price = form.cleaned_data.get('price')
            item.description = form.cleaned_data.get('description')
            item.save()
            return redirect('/items/' + str(pk))
        return super().form_valid(form)

items/templates/items/additems.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}" />
        <title>Adding items</title>
        <script defer>
            function resetForm() {
                document.getElementById("formContainer").reset();
                alert("Item added");
            }
        </script>
    </head>
    <body>
        <div id="navbar">
            <h3>
                <a href="/home">Fakijiji</a>
                <a href="/items" style="margin-left: 1em; font-weight: normal">Items</a>
            </h3>
            <div id="right">
                <p class="rightitem" style="cursor: default">Balance: {{ userprofile.balance }}$</p>
                <a class="rightitem" href="/">Sign out</a>
                <a class="rightitem" href="/items/additems/">Add Item</a>
                <a href="/profile">
                    <img id="profile" src="{% static userprofile.avatar %}" alt="" />
                </a>
                {% if userprofile == None %}
                <a>
                    <img id="profile" src="{% static 'avatar/defaultavatar.png' %}" alt="" />
                </a>
                {% endif %}
            </div>
        </div>
        <button id="back" onclick="window.location.href='/items/'">Back</button>
        <div id="header" class="small">
            <div>
                <h1>Adding items</h1>
            </div>
        </div>
        <div id="formContainer">
            <form enctype="multipart/form-data" method="post">
                {% csrf_token %} {{ form }}
                <button class="button" type="submit" value="Add Item" onclick="resetForm()">Add Item</button>
                <button class="button" type="reset" value="Reset">Reset</button>
            </form>
        </div>
    </body>
</html>

items/templates/items/buyItem.html
{% load static %}

<html>
    <head>
        <title>Buy item</title>
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}" />
        {% if sufficientBalance == False %}
        <script defer>
            alert("You do not have sufficient balance to buy this item.\nPlease add $");
            window.location.href = "/profile/addBalance/";
        </script>
        {% endif %}
    </head>
    <body>
        <div id="navbar">
            <h3>
                <a href="/home">Fakijiji</a>
                <a href="/items" style="margin-left: 1em; font-weight: normal">Items</a>
            </h3>
            <div id="right">
                <p class="rightitem" style="cursor: default">Balance: {{ userprofile.balance }}$</p>
                <a class="rightitem" href="/">Sign out</a>
                <a class="rightitem" href="/items/additems/">Add Item</a>
                <a href="/profile">
                    <img id="profile" src="{% static userprofile.avatar %}" alt="" />
                </a>
                {% if userprofile == None %}
                <a>
                    <img id="profile" src="{% static 'avatar/defaultavatar.png' %}" alt="" />
                </a>
                {% endif %}
            </div>
        </div>
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to buy {{ item.title }} for {{item.price}}$?</p>
            <input type="submit" value="Confirm" />
        </form>
    </body>
</html>

items/templates/items/buyitem.html
{% load static %}

<html>
    <head>
        <title>Buy item</title>
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}" />
        {% if sufficientBalance == False %}
        <script defer>
            alert("You do not have sufficient balance to buy this item.\nPlease add $");
            window.location.href = "/profile/addBalance/";
        </script>
        {% endif %}
    </head>
    <body>
        <div id="navbar">
            <h3>
                <a href="/home">Fakijiji</a>
                <a href="/items" style="margin-left: 1em; font-weight: normal">Items</a>
            </h3>
            <div id="right">
                <p class="rightitem" style="cursor: default">Balance: {{ userprofile.balance }}$</p>
                <a class="rightitem" href="/">Sign out</a>
                <a class="rightitem" href="/items/additems/">Add Item</a>
                <a href="/profile">
                    <img id="profile" src="{% static userprofile.avatar %}" alt="" />
                </a>
                {% if userprofile == None %}
                <a>
                    <img id="profile" src="{% static 'avatar/defaultavatar.png' %}" alt="" />
                </a>
                {% endif %}
            </div>
        </div>
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to buy {{ item.title }} for {{item.price}}$?</p>
            <input type="submit" value="Confirm" />
        </form>
    </body>
</html>

items/templates/items/customeritems.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Customer</title>
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}" />
        <script defer>
            function viewitem(item) {
                print("test");
            }
        </script>
    </head>
    <body>
        <div id="navbar">
            <h3>
                <a href="/home">Fakijiji</a>
                <a href="/items" style="margin-left: 1em; font-weight: normal">Items</a>
            </h3>
            <div id="right">
                <p class="rightitem" style="cursor: default">Balance: {{ userprofile.balance }}$</p>
                <a class="rightitem" href="/">Sign out</a>
                <a class="rightitem" href="/items/additems/">Add Item</a>
                <a href="/profile">
                    <img id="profile" src="{% static userprofile.avatar %}" alt="" />
                </a>
                {% if userprofile == None %}
                <a>
                    <img id="profile" src="{% static 'avatar/defaultavatar.png' %}" alt="" />
                </a>
                {% endif %}
            </div>
        </div>
        <h2>Customer | Signed in as {{ username }}</h2>
        {% if user.is_authenticated %} {% block page_content %}
        <h2 id="page">Items Page</h2>
        <br />
        <form method="post">
            {% csrf_token %}
            <div style="display: inline-block">
                <input type="text" placeholder="Search..." name="search" />
                <button type="submit">Search</button>
            </div>
        </form>
        <div class="itemsscroll">
            <div class="items">
                {% for item in items %}
                <div class="card">
                    <div>
                        <a href="{% url 'item:view_item' item.id %}">
                            <img class="card-img-top" src="{% static item.img %}" />
                        </a>
                    </div>
                    <div class="card-body">
                        <h4 class="card-title">{{ item.title }} <span class="sold">{{ item.sold|yesno:"Sold,Not Sold" }}</span></h4>
                        <p class="card-text">Price: {{ item.price }}</p>
                    </div>
                    <form method="post" action="{% url 'item:like_item' item.id %}">
                        {% csrf_token %}
                        <button class="like" type="submit" name="like" value="{{ item.id }}">like &lt;3 {{ item.likes }}</button>
                    </form>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endblock %} {% else %}
        <button onclick="window.location.href='/home/login'">Login</button>
        {% endif %}
    </body>
</html>

items/templates/items/deleteItem.html
{% load static %}

<html>
    <head>
        <title>Delete Item</title>
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}" />
    </head>
    <body>
        <div id="navbar">
            <h3>
                <a href="/home">Fakijiji</a>
                <a href="/items" style="margin-left: 1em; font-weight: normal">Items</a>
            </h3>
            <div id="right">
                <p class="rightitem" style="cursor: default">Balance: {{ userprofile.balance }}$</p>
                <a class="rightitem" href="/">Sign out</a>
                <a class="rightitem" href="/items/additems/">Add Item</a>
                <a href="/profile">
                    <img id="profile" src="{% static userprofile.avatar %}" alt="" />
                </a>
                {% if userprofile == None %}
                <a>
                    <img id="profile" src="{% static 'avatar/defaultavatar.png' %}" alt="" />
                </a>
                {% endif %}
            </div>
        </div>
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete "{{ object.title }}"?</p>
            <input type="submit" value="Confirm" />
        </form>
    </body>
</html>

items/templates/items/deleteitem.html
{% load static %}

<html>
    <head>
        <title>Delete Item</title>
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}" />
    </head>
    <body>
        <div id="navbar">
            <h3>
                <a href="/home">Fakijiji</a>
                <a href="/items" style="margin-left: 1em; font-weight: normal">Items</a>
            </h3>
            <div id="right">
                <p class="rightitem" style="cursor: default">Balance: {{ userprofile.balance }}$</p>
                <a class="rightitem" href="/">Sign out</a>
                <a class="rightitem" href="/items/additems/">Add Item</a>
                <a href="/profile">
                    <img id="profile" src="{% static userprofile.avatar %}" alt="" />
                </a>
                {% if userprofile == None %}
                <a>
                    <img id="profile" src="{% static 'avatar/defaultavatar.png' %}" alt="" />
                </a>
                {% endif %}
            </div>
        </div>
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete "{{ object.title }}"?</p>
            <input type="submit" value="Confirm" />
        </form>
    </body>
</html>

items/templates/items/guestItems.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Guest</title>
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}" />
        <script defer>
            function myFunction(item) {
                alert("accesing item" + item);
            }
            function search(name) {}
        </script>
    </head>
    <body>
        <div id="navbar">
            <h3><a href="/home">Fakijiji</a></h3>
            <p>Neil Fisher, Christian Bula, Jei wen Wu, Mate Barabas made with love ❤️ by team Dyson</p>
            <div id="right">
                <a href="/profile">
                    <a class="rightitem" href="/home">Sign in</a>
                    <img id="profile" src="{% static 'avatar/defaultavatar.png' %}" alt="" />
                </a>
            </div>
        </div>
        <h1>Guest Items!</h1>
        <h4 style="margin: 0">You must be signed in to interact with the items</h4>
        {% block page_content %}
        <h2>Items</h2>
        <br />
        <form method="post">
            {% csrf_token %}
            <div style="display: inline-block">
                <input type="text" placeholder="Search..." name="search" />
                <button type="submit">Search</button>
            </div>
        </form>
        <div class="itemsscroll">
            <div class="items">
                {% for item in items %}
                <div class="card">
                    <div>
                        <a href="{% url 'item:view_item' item.id %}">
                            <img class="card-img-top" src="{% static item.img %}" />
                        </a>
                    </div>
                    <div class="card-body">
                        <h4 class="card-title">{{ item.title }} <span class="sold">{{ item.sold|yesno:"Sold,Not Sold" }}</span></h4>
                        <p class="card-text">Price: {{ item.price }}</p>
                    </div>
                    <form method="post" action="{% url 'item:like_item' item.id %}">
                        {% csrf_token %}
                        <button class="like" type="submit" name="like" value="{{ item.id }}">like &lt;3 {{ item.likes }}</button>
                    </form>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endblock %}
    </body>
</html>

items/templates/items/guestitems.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Guest</title>
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}" />
        <script defer>
            function myFunction(item) {
                alert("accesing item" + item);
            }
            function search(name) {}
        </script>
    </head>
    <body>
        <div id="navbar">
            <h3><a href="/home">Fakijiji</a></h3>
            <p>Neil Fisher, Christian Bula, Jei wen Wu, Mate Barabas made with love ❤️ by team Dyson</p>
            <div id="right">
                <a href="/profile">
                    <a class="rightitem" href="/home">Sign in</a>
                    <img id="profile" src="{% static 'avatar/defaultavatar.png' %}" alt="" />
                </a>
            </div>
        </div>
        <h1>Guest Items!</h1>
        <h4 style="margin: 0">You must be signed in to interact with the items</h4>
        {% block page_content %}
        <h2>Items</h2>
        <br />
        <form method="post">
            {% csrf_token %}
            <div style="display: inline-block">
                <input type="text" placeholder="Search..." name="search" />
                <button type="submit">Search</button>
            </div>
        </form>
        <div class="itemsscroll">
            <div class="items">
                {% for item in items %}
                <div class="card">
                    <div>
                        <a href="{% url 'item:view_item' item.id %}">
                            <img class="card-img-top" src="{% static item.img %}" />
                        </a>
                    </div>
                    <div class="card-body">
                        <h4 class="card-title">{{ item.title }} <span class="sold">{{ item.sold|yesno:"Sold,Not Sold" }}</span></h4>
                        <p class="card-text">Price: {{ item.price }}</p>
                    </div>
                    <form method="post" action="{% url 'item:like_item' item.id %}">
                        {% csrf_token %}
                        <button class="like" type="submit" name="like" value="{{ item.id }}">like &lt;3 {{ item.likes }}</button>
                    </form>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endblock %}
    </body>
</html>

items/templates/items/item.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}" />
        <title>Item</title>
        <script defer></script>
    </head>
    <body>
        <div id="navbar">
            <button id="back" onclick="window.location.href='/items/'">Back</button>
            <h3>
                <a href="/home">Fakijiji</a>
                <a href="/items" style="margin-left: 1em; font-weight: normal">Items</a>
            </h3>
            <div id="right">
                <p class="rightitem" style="cursor: default">Balance: {{ userprofile.balance }}$</p>
                <a class="rightitem" href="/">Sign out</a>
                <a class="rightitem" href="/items/additems/">Add Item</a>
                <a href="/profile">
                    <img id="profile" src="{% static userprofile.avatar %}" alt="" />
                </a>
                {% if userprofile == None %}
                <a>
                    <img id="profile" src="{% static 'avatar/defaultavatar.png' %}" alt="" />
                </a>
                {% endif %}
            </div>
            </div>
        </div>
        <h2>{{ item.title }}</h2>
        <img id="image" class="card-img-top" style="height: 500px; width: auto; margin: 1em" src="{% static item.img %}" />
        <div id="infoContainer" class="itemInfo">
            <div id="price">Price: {{ item.price }}</div>
            <div id="likes">Likes: {{ item.likes }}</div>
            <div id="ratings">Rating: {{ item.rate }}</div>
            <div id="sold">Sold: {{ item.sold|yesno:"Sold,Not Sold" }}</div>
            <div id="user">Owner: {{ item.user }}</div>
            <div id="description">Description: {{ item.description }}</div>
        </div>
        <div>
            <form method="post" action="{% url 'item:like_item' item.id %}">
                {% csrf_token %}
                <button class="like" type="submit" name="like" value="{{ item.id }}">like &lt;3 {{ item.likes }}</button>
            </form>
            <br>
            <form method="post" action="{% url 'item:rate_item' item.id %}" value="{{ item.id }}">
                {% csrf_token %}
                <div style="display: inline-flex; flex-direction: row;">
                    <label for="rate">Rate Item: </label>
                    <div style="display: flex; flex-direction: column;">
                        <p style="margin: 0; line-height: 10%;">{{ item.rate }}</p>
                        <input class="like" type="range" name="rate" step="0.5" value="{{ item.rate }}" min="0.0" max="5.0">
                    </div>
                    <button class="like" type="submit" name="ratebtn" value="{{ item.id }}">Rate</button>
                </div>
            </form>
        </div>
        {% if item.sold == False %}
            {% if user.id == item.user_id %}
            <a class="edit" href="{% url 'item:modify_item' item.id %}">Modify</a>
            <a class="edit" href="{% url 'item:delete_item' item.id %}">Delete</a>
            {% elif userprofile != None %} 
            <a class="edit" href="{% url 'item:buy_item' item.id %}">Buy</a>
            {% else %}
            <a class="edit" href="/home/">Login to buy</a>
            {% endif %}
        {% endif %}
    </body>
</html>

items/templates/items/modifyItem.html
{% load static %}

<html>
    <head>
        <title>Modify Item</title>
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}" />
    </head>
    <body>
        <div id="navbar">
            <h3>
                <a href="/home">Fakijiji</a>
                <a href="/items" style="margin-left: 1em; font-weight: normal">Items</a>
            </h3>
            <div id="right">
                <p class="rightitem" style="cursor: default">Balance: {{ userprofile.balance }}$</p>
                <a class="rightitem" href="/">Sign out</a>
                <a class="rightitem" href="/items/additems/">Add Item</a>
                <a href="/profile">
                    <img id="profile" src="{% static userprofile.avatar %}" alt="" />
                </a>
                {% if userprofile == None %}
                <a>
                    <img id="profile" src="{% static 'avatar/defaultavatar.png' %}" alt="" />
                </a>
                {% endif %}
            </div>
        </div>
        <div id="formContainer">
            <h3>{{ item.title }}</h3>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %} {{ form }}
                <input type="submit" value="Modify" />
            </form>
        </div>
    </body>
</html>

items/templates/items/modifyitem.html
{% load static %}

<html>
    <head>
        <title>Modify Item</title>
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}" />
    </head>
    <body>
        <div id="navbar">
            <h3>
                <a href="/home">Fakijiji</a>
                <a href="/items" style="margin-left: 1em; font-weight: normal">Items</a>
            </h3>
            <div id="right">
                <p class="rightitem" style="cursor: default">Balance: {{ userprofile.balance }}$</p>
                <a class="rightitem" href="/">Sign out</a>
                <a class="rightitem" href="/items/additems/">Add Item</a>
                <a href="/profile">
                    <img id="profile" src="{% static userprofile.avatar %}" alt="" />
                </a>
                {% if userprofile == None %}
                <a>
                    <img id="profile" src="{% static 'avatar/defaultavatar.png' %}" alt="" />
                </a>
                {% endif %}
            </div>
        </div>
        <div id="formContainer">
            <h3>{{ item.title }}</h3>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %} {{ form }}
                <input type="submit" value="Modify" />
            </form>
        </div>
    </body>
</html>